version: "3.8"

services:
  nvidia_docker:
    build:
      context: .
      shm_size: '10gb'
    shm_size: '10gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./:/root
      - /home/dataset:/root/dataset
      - /home/nitstu/Cloud/:/root/Cloud

    working_dir: /root
    command: ["/bin/bash"]

